service: staking-balance-checker

provider:
  name: aws
  runtime: ruby2.5
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::${env:BUCKET_NAME}/*"

functions:
  staking_balance_check:
    handler: handler.staking_balance_check
    environment:
      SLACK_ENDPOINT: ${env:SLACK_ENDPOINT}
      BUCKET_NAME: ${env:BUCKET_NAME}
